version: '3'

services:
  api-server:
    build:
      context: ./srv
      dockerfile: Dockerfile
      target: development
    image: server-side:${ENV}
    container_name: api
    ports:
      - 3000:3000
    networks:
      - test_net
    depends_on:
      - postgres
    volumes:
      - ./srv:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    env_file:
      - ./srv/.env.${ENV}
    command: npm run start:dev

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root456
      POSTGRES_DB: test_pagination
    ports:
      - 5432:5432
    networks:
      - test_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: development
    image: client-side:${ENV}
    container_name: web
    ports:
      - 3001:3001
    networks:
      - test_net
    depends_on:
      - api-server
    volumes:
      - ./web:/app
      - /app/node_modules
    restart: always
    # env_file:
    #   - ./web/.env.${ENV}
    command: npm run dev

networks:
  test_net:
    driver: bridge

volumes:
  postgres_data: